image: kaiwinter/docker-java8-maven
# image: maven:3.3.9-jdk-8

# most of this taken from https://stackoverflow.com/questions/37785154/how-to-enable-maven-artifact-caching-for-gitlab-ci-runner

cache:
  paths:
    - .m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

build-job:
  stage: build
  script:
    - "mvn clean compile -f tdt4140-gr1817/pom.xml $MAVEN_CLI_OPTS"

unittest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn package -f tdt4140-gr1817/pom.xml $MAVEN_CLI_OPTS"
    - "cat tdt4140-gr1817/app.core/target/site/jacoco/index.html"

integrationtest-job:
  stage: test
  dependencies:
    - build-job
  variables:
    HEADLESS_TESTFX: "-Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    MAVEN_OPTS: "$${MAVEN_OPTS} -Dmaven.repo.local=.m2/repository -Djava.awt.headless=true $HEADLESS_TESTFX"
  script:
    - export
    - "mvn verify -f tdt4140-gr1817/pom.xml $MAVEN_CLI_OPTS"
