image: krissrex/docker-java8-maven-testfxmonocle:1.0

cache:
  paths:
    - .m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

build-job:
  stage: build
  script:
    - "mvn clean compile -f tdt4140-gr1817/pom.xml $MAVEN_CLI_OPTS"

unittest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn verify -f tdt4140-gr1817/pom.xml $MAVEN_CLI_OPTS -P unit-test,headless -DskipDev=true"
    - "cat tdt4140-gr1817/reporting/target/site/jacoco-aggregate/index.html 2>/dev/null"

integrationtest-job:
  stage: test
  dependencies:
    - build-job
  script:
    # surefire blocks propagation of properties that are not set inside argLine
    - "mvn verify -f tdt4140-gr1817/pom.xml $MAVEN_CLI_OPTS -P integration-test,headless -DskipDev=true"
